### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by AiYanLang** [cupslab/neural_network_cracking#24]
I trained a LSTM network from my own password list.But when I tried to use the network to enumerate passwords, I got a ZeroDivisionError like this:
Traceback (most recent call last):
  File "../pwd_guess.py", line 3219, in <module>
    main_bundle()
  File "../pwd_guess.py", line 3215, in <lambda>
    main_bundle = lambda: main(args)
  File "../pwd_guess.py", line 3151, in main
    guess(args, config)
  File "../pwd_guess.py", line 3093, in guess
    .add_file(args['enumerate_ofile'])).build()
  File "../pwd_guess.py", line 2776, in build
    model_or_serializer, self.config, self.ostream)
  File "../pwd_guess.py", line 2240, in __init__
    self.output_serializer = self.make_serializer()
  File "../pwd_guess.py", line 2295, in make_serializer
    answer = PasswordTemplateSerializer(self.config, answer)
  File "../pwd_guess.py", line 1878, in __init__
    self.beg_cache = self.cache_freqs(self.beginning_char_frequencies)
  File "../pwd_guess.py", line 1896, in cache_freqs
    freqs, template_char, preimage)
  File "../pwd_guess.py", line 1901, in _calc
    lambda c: freqs[c], self.preimage[template_char]))
ZeroDivisionError: division by zero

**Comment by m33x** [comment]
To be able to reproduce this issue, the authors of the software will need more information.

1) The configuration used and the command you ran

2) Any additional information such as a description of the steps taken, the inputfiles (trained network, password file), OS version, Python version, and installed modules etc.

That being said, simply posting the exception here, will not result in any response or fix by the authors.

Full disclosure: I’m not affiliated with the authors‘ institution or their projects.

**Comment by AiYanLang** [comment]
Thank you for your response!
I have attached the trainconfig and trainlog and guessconfig. 
I use the command"python3 ../pwd_guess.py --config-args train_config.json" to train the network, and then use the command"python3 ../pwd_guess.py --config-args enumerate_config.json".
The passwords in the password file only use chars which listed in char_bag in the enumerate_config.json. If I don't appoint char_bag, I get the error too.
I use docker to run the project.The OS version is ubuntu16.04.1, the Python version is 3.5.2, the modules version as follows:
  Cython==0.25.2
  h5py==2.6.0
  Keras==0.2.0
  numpy==1.12.1
  PyYAML==3.12
  scikit-learn==0.18.1
  scipy==1.2.1
  seya==0.1.0
  six==1.12.0
  sqlitedict==1.5.0
  Theano==0.8.2
  virtualenv==15.0.1

#####train_config.json#####
{
    "args" : {
        "arch_file" : "arch.json",
        "weight_file" : "weight.h5",
        "log_file" : "train_log.txt",
        "pwd_file" : [
            "../65825pwd.txt"
        ],
        "pwd_format" : [
            "list"
        ]
    },
    "config" : {
        "training_chunk" : 1000,
        "training_main_memory_chunk": 10000000,
        "min_len" : 3,
        "max_len" : 20,
        "context_length" : 10,
        "chunk_print_interval" : 100,
        "layers" : 3,
        "hidden_size" : 1000,
        "generations" : 20,
        "training_accuracy_threshold" : -1,
        "train_test_ratio" : 20,
        "model_type" : "LSTM",
        "train_backwards" : true,
        "dense_layers" : 2,
        "dense_hidden_size" : 512,
        "secondary_training" : false,
        "simulated_frequency_optimization" : false,
        "randomize_training_order" : true,
        "uppercase_character_optimization" : true,
        "rare_character_optimization" : true,
        "rare_character_optimization_guessing" : true,
        "no_end_word_cache" : true,
        "intermediate_fname" : "intermediate_data.sqlite",
        "save_model_versioned" : true
    }
}

#####train_log.txt#####
2019-04-15 14:26:56,442 INFO: Beginning...
2019-04-15 14:26:56,442 INFO: Arguments: {
    "log_file": "train_log.txt",
    "stats_only": false,
    "config_cmdline": "",
    "pwd_file": [
        "../65825pwd.txt"
    ],
    "args": null,
    "profile": null,
    "forked": null,
    "config": null,
    "enumerate_ofile": null,
    "retrain": false,
    "log_level": "info",
    "config_args": "train_config.json",
    "version": false,
    "arch_file": "arch.json",
    "train_secondary_only": false,
    "calc_probability_only": false,
    "weight_file": "weight.h5",
    "pre_processing_only": false,
    "pwd_format": [
        "list"
    ]
}
2019-04-15 14:26:56,451 INFO: Version: d49b7b30b0d0bae3e0b074402fe4ee47d57f5185
2019-04-15 14:26:56,451 INFO: Configuration: {
    "cleanup_guesser_files": true,
    "training_main_memory_chunksize": 1000000,
    "intermediate_fname": "intermediate_data.sqlite",
    "fork_length": 2,
    "simulated_frequency_optimization": false,
    "rare_character_optimization": true,
    "toc_chunk_size": 1000,
    "uppercase_character_optimization": true,
    "no_end_word_cache": true,
    "secondary_train_sets": null,
    "preprocess_trie_on_disk": false,
    "model_optimizer": "adam",
    "pwd_list_weights": {},
    "rare_character_optimization_guessing": true,
    "use_mmap": true,
    "dense_hidden_size": 512,
    "trie_serializer_type": "reg",
    "trie_implementation": null,
    "max_gpu_prediction_size": 25000,
    "lower_probability_threshold": 1e-05,
    "password_test_fname": null,
    "dropouts": false,
    "enforced_policy": "basic",
    "secondary_training_save_freqs": false,
    "trie_serializer_encoding": "utf8",
    "parallel_guessing": false,
    "random_walk_confidence_bound_z_value": 1.96,
    "most_common_token_count": 2000,
    "layers": 3,
    "preprocess_trie_on_disk_buff_size": 100000,
    "context_length": 10,
    "max_len": 20,
    "freeze_feature_layers_during_secondary_training": true,
    "secondary_training": false,
    "bidirectional_rnn": false,
    "dropout_ratio": 0.25,
    "save_model_versioned": true,
    "relevel_not_matching_passwords": true,
    "trie_fname": ":memory:",
    "gpu_fork_bias": 2,
    "final_schedule_ratio": 0.05,
    "random_walk_upper_bound": 10,
    "save_always": true,
    "freq_format": "hex",
    "random_walk_confidence_percent": 5,
    "dense_layers": 2,
    "model_type": "LSTM",
    "tokenize_words": false,
    "padding_character": null,
    "trie_intermediate_storage": ":memory:",
    "compute_stats": false,
    "min_len": 3,
    "train_test_ratio": 20,
    "probability_striation": false,
    "rare_character_lowest_threshold": 20,
    "tokenize_guessing": true,
    "hidden_size": 1000,
    "training_main_memory_chunk": 10000000,
    "fuzzy_training_smoothing": false,
    "cpu_limit": 8,
    "guesser_class": null,
    "guessing_secondary_training": false,
    "random_walk_seed_num": 1000,
    "scheduled_sampling": false,
    "prob_striation_step": 0.05,
    "chunk_size_guesser": 1000,
    "guesser_intermediate_directory": "guesser_files",
    "guess_serialization_method": "human",
    "deep_model": false,
    "training_accuracy_threshold": -1,
    "char_bag": "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789~!@#$%^&*(),.<>/?'\"{}[]\\|-_=+;: `\n",
    "chunk_print_interval": 100,
    "train_backwards": true,
    "generations": 20,
    "randomize_training_order": true,
    "training_chunk": 1000
}
2019-04-15 14:26:56,451 INFO: Reading training set...
2019-04-15 14:26:56,803 INFO: Filtered 0 of 65825 passwords
2019-04-15 14:26:56,803 INFO: opening Sqlite table 'unnamed' in intermediate_data.sqlite
2019-04-15 14:26:56,805 INFO: Rare characters: ['~', '$', '%', '^', '(', ',', '<', '>', '/', '?', "'", '"', '{', '}', '[', ']', '\\', '|', '=', ';']
2019-04-15 14:26:56,806 INFO: Longest pwd is : 15 characters long
2019-04-15 14:26:56,806 INFO: opening Sqlite table 'unnamed' in intermediate_data.sqlite
2019-04-15 14:26:56,807 INFO: opening Sqlite table 'unnamed' in intermediate_data.sqlite
2019-04-15 14:26:56,809 INFO: opening Sqlite table 'unnamed' in intermediate_data.sqlite
2019-04-15 14:26:56,810 INFO: Done reading passwords...
2019-04-15 14:26:56,811 INFO: Preprocessor type None...
2019-04-15 14:26:57,365 INFO: Regular trainer
2019-04-15 14:26:57,365 INFO: opening Sqlite table 'unnamed' in intermediate_data.sqlite
2019-04-15 14:26:57,367 INFO: Training model with primary data
2019-04-15 14:26:57,367 INFO: Building model...
2019-04-15 14:27:30,789 ERROR: Optimization failure due to: local_subtensor_merge
2019-04-15 14:27:30,789 ERROR: node: Subtensor{::int64}(Subtensor{int64::}.0, Constant{-1})
2019-04-15 14:27:30,789 ERROR: TRACEBACK:
2019-04-15 14:27:30,790 ERROR: Traceback (most recent call last):
  File "/root/Theano-rel-0.8.2/theano/gof/opt.py", line 1807, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/root/Theano-rel-0.8.2/theano/gof/toolbox.py", line 309, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/root/Theano-rel-0.8.2/theano/gof/fg.py", line 561, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Subtensor{::int64}.0, Subtensor{int64:int64:int64}.0, TensorType(float32, (True, False, False)), TensorType(float32, 3D), 'local_subtensor_merge')

2019-04-15 14:27:30,818 ERROR: Optimization failure due to: local_subtensor_merge
2019-04-15 14:27:30,818 ERROR: node: Subtensor{::int64}(Subtensor{int64::}.0, Constant{-1})
2019-04-15 14:27:30,818 ERROR: TRACEBACK:
2019-04-15 14:27:30,818 ERROR: Traceback (most recent call last):
  File "/root/Theano-rel-0.8.2/theano/gof/opt.py", line 1807, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/root/Theano-rel-0.8.2/theano/gof/toolbox.py", line 309, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/root/Theano-rel-0.8.2/theano/gof/fg.py", line 561, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Subtensor{::int64}.0, Subtensor{int64:int64:int64}.0, TensorType(float32, (True, False, False)), TensorType(float32, 3D), 'local_subtensor_merge')

2019-04-15 14:27:30,843 ERROR: Optimization failure due to: local_subtensor_merge
2019-04-15 14:27:30,844 ERROR: node: Subtensor{::int64}(Subtensor{int64::}.0, Constant{-1})
2019-04-15 14:27:30,844 ERROR: TRACEBACK:
2019-04-15 14:27:30,844 ERROR: Traceback (most recent call last):
  File "/root/Theano-rel-0.8.2/theano/gof/opt.py", line 1807, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/root/Theano-rel-0.8.2/theano/gof/toolbox.py", line 309, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/root/Theano-rel-0.8.2/theano/gof/fg.py", line 561, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Subtensor{::int64}.0, Subtensor{int64:int64:int64}.0, TensorType(float32, (True, False, False)), TensorType(float32, 3D), 'local_subtensor_merge')

2019-04-15 14:27:30,870 ERROR: Optimization failure due to: local_subtensor_merge
2019-04-15 14:27:30,871 ERROR: node: Subtensor{::int64}(Subtensor{int64::}.0, Constant{-1})
2019-04-15 14:27:30,874 ERROR: TRACEBACK:
2019-04-15 14:27:30,874 ERROR: Traceback (most recent call last):
  File "/root/Theano-rel-0.8.2/theano/gof/opt.py", line 1807, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/root/Theano-rel-0.8.2/theano/gof/toolbox.py", line 309, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/root/Theano-rel-0.8.2/theano/gof/fg.py", line 561, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Subtensor{::int64}.0, Subtensor{int64:int64:int64}.0, TensorType(float32, (True, False, False)), TensorType(float32, 3D), 'local_subtensor_merge')

2019-04-15 14:28:41,953 ERROR: Optimization failure due to: local_subtensor_merge
2019-04-15 14:28:41,953 ERROR: node: Subtensor{::int64}(Subtensor{int64::}.0, Constant{-1})
2019-04-15 14:28:41,953 ERROR: TRACEBACK:
2019-04-15 14:28:41,953 ERROR: Traceback (most recent call last):
  File "/root/Theano-rel-0.8.2/theano/gof/opt.py", line 1807, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/root/Theano-rel-0.8.2/theano/gof/toolbox.py", line 309, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/root/Theano-rel-0.8.2/theano/gof/fg.py", line 561, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Subtensor{::int64}.0, Subtensor{int64:int64:int64}.0, TensorType(float32, (True, False, False)), TensorType(float32, 3D), 'local_subtensor_merge')

2019-04-15 14:28:41,976 ERROR: Optimization failure due to: local_subtensor_merge
2019-04-15 14:28:41,976 ERROR: node: Subtensor{::int64}(Subtensor{int64::}.0, Constant{-1})
2019-04-15 14:28:41,976 ERROR: TRACEBACK:
2019-04-15 14:28:41,977 ERROR: Traceback (most recent call last):
  File "/root/Theano-rel-0.8.2/theano/gof/opt.py", line 1807, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/root/Theano-rel-0.8.2/theano/gof/toolbox.py", line 309, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/root/Theano-rel-0.8.2/theano/gof/fg.py", line 561, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Subtensor{::int64}.0, Subtensor{int64:int64:int64}.0, TensorType(float32, (True, False, False)), TensorType(float32, 3D), 'local_subtensor_merge')

2019-04-15 14:28:42,000 ERROR: Optimization failure due to: local_subtensor_merge
2019-04-15 14:28:42,001 ERROR: node: Subtensor{::int64}(Subtensor{int64::}.0, Constant{-1})
2019-04-15 14:28:42,001 ERROR: TRACEBACK:
2019-04-15 14:28:42,001 ERROR: Traceback (most recent call last):
  File "/root/Theano-rel-0.8.2/theano/gof/opt.py", line 1807, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/root/Theano-rel-0.8.2/theano/gof/toolbox.py", line 309, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/root/Theano-rel-0.8.2/theano/gof/fg.py", line 561, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Subtensor{::int64}.0, Subtensor{int64:int64:int64}.0, TensorType(float32, (True, False, False)), TensorType(float32, 3D), 'local_subtensor_merge')

2019-04-15 14:28:42,025 ERROR: Optimization failure due to: local_subtensor_merge
2019-04-15 14:28:42,025 ERROR: node: Subtensor{::int64}(Subtensor{int64::}.0, Constant{-1})
2019-04-15 14:28:42,025 ERROR: TRACEBACK:
2019-04-15 14:28:42,025 ERROR: Traceback (most recent call last):
  File "/root/Theano-rel-0.8.2/theano/gof/opt.py", line 1807, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "/root/Theano-rel-0.8.2/theano/gof/toolbox.py", line 309, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/root/Theano-rel-0.8.2/theano/gof/fg.py", line 561, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Subtensor{::int64}.0, Subtensor{int64:int64:int64}.0, TensorType(float32, (True, False, False)), TensorType(float32, 3D), 'local_subtensor_merge')

2019-04-15 14:30:10,006 INFO: Done compiling model. Beginning training...
2019-04-15 14:30:10,006 INFO: Generation 1
2019-04-15 14:30:12,995 INFO: Chunk 0. Each chunk is size 9603
2019-04-15 14:30:12,995 INFO: Train loss 3.9317753314971924. Test loss 3.9161899089813232. Test accuracy 0.15833333333333333.
2019-04-15 14:32:50,719 INFO: Generation accuracy: 0.155018584068
2019-04-15 14:32:50,720 INFO: Saving model architecture
2019-04-15 14:32:50,720 INFO: Saving model weights
2019-04-15 14:32:50,895 INFO: Done saving model
2019-04-15 14:32:50,895 INFO: Generation 2
2019-04-15 14:32:53,876 INFO: Chunk 0. Each chunk is size 9591
2019-04-15 14:32:53,876 INFO: Train loss 2.797980308532715. Test loss 2.7107789516448975. Test accuracy 0.22129436325678498.
2019-04-15 14:35:32,293 INFO: Generation accuracy: 0.194328683537
2019-04-15 14:35:32,293 INFO: Saving model architecture
2019-04-15 14:35:32,294 INFO: Saving model weights
2019-04-15 14:35:32,381 INFO: Done saving model
2019-04-15 14:35:32,381 INFO: Generation 3
2019-04-15 14:35:35,358 INFO: Chunk 0. Each chunk is size 9549
2019-04-15 14:35:35,358 INFO: Train loss 2.725562572479248. Test loss 2.6997182369232178. Test accuracy 0.18658280922431866.
2019-04-15 14:38:12,496 INFO: Generation accuracy: 0.204964250562
2019-04-15 14:38:12,497 INFO: Saving model architecture
2019-04-15 14:38:12,497 INFO: Saving model weights
2019-04-15 14:38:12,586 INFO: Done saving model
2019-04-15 14:38:12,586 INFO: Generation 4
2019-04-15 14:38:15,539 INFO: Chunk 0. Each chunk is size 9502
2019-04-15 14:38:15,539 INFO: Train loss 2.6198770999908447. Test loss 2.6331429481506348. Test accuracy 0.2.
2019-04-15 14:40:52,925 INFO: Generation accuracy: 0.226937285014
2019-04-15 14:40:52,926 INFO: Saving model architecture
2019-04-15 14:40:52,926 INFO: Saving model weights
2019-04-15 14:40:53,015 INFO: Done saving model
2019-04-15 14:40:53,015 INFO: Generation 5
2019-04-15 14:40:55,975 INFO: Chunk 0. Each chunk is size 9550
2019-04-15 14:40:55,975 INFO: Train loss 2.557020425796509. Test loss 2.49861741065979. Test accuracy 0.27253668763102723.
2019-04-15 14:43:33,116 INFO: Generation accuracy: 0.257170957304
2019-04-15 14:43:33,116 INFO: Saving model architecture
2019-04-15 14:43:33,116 INFO: Saving model weights
2019-04-15 14:43:33,207 INFO: Done saving model
2019-04-15 14:43:33,207 INFO: Generation 6
2019-04-15 14:43:36,208 INFO: Chunk 0. Each chunk is size 9652
2019-04-15 14:43:36,208 INFO: Train loss 2.4769842624664307. Test loss 2.438237428665161. Test accuracy 0.26141078838174275.
2019-04-15 14:46:13,468 INFO: Generation accuracy: 0.278025107407
2019-04-15 14:46:13,468 INFO: Saving model architecture
2019-04-15 14:46:13,469 INFO: Saving model weights
2019-04-15 14:46:13,561 INFO: Done saving model
2019-04-15 14:46:13,561 INFO: Generation 7
2019-04-15 14:46:16,533 INFO: Chunk 0. Each chunk is size 9512
2019-04-15 14:46:16,533 INFO: Train loss 2.4267616271972656. Test loss 2.3440730571746826. Test accuracy 0.30526315789473685.
2019-04-15 14:48:53,672 INFO: Generation accuracy: 0.28812088369
2019-04-15 14:48:53,672 INFO: Saving model architecture
2019-04-15 14:48:53,673 INFO: Saving model weights
2019-04-15 14:48:53,767 INFO: Done saving model
2019-04-15 14:48:53,767 INFO: Generation 8
2019-04-15 14:48:56,741 INFO: Chunk 0. Each chunk is size 9613
2019-04-15 14:48:56,741 INFO: Train loss 2.3907411098480225. Test loss 2.4224367141723633. Test accuracy 0.2604166666666667.
2019-04-15 14:51:34,116 INFO: Generation accuracy: 0.298506543117
2019-04-15 14:51:34,116 INFO: Saving model architecture
2019-04-15 14:51:34,116 INFO: Saving model weights
2019-04-15 14:51:34,205 INFO: Done saving model
2019-04-15 14:51:34,205 INFO: Generation 9
2019-04-15 14:51:37,186 INFO: Chunk 0. Each chunk is size 9635
2019-04-15 14:51:37,186 INFO: Train loss 2.3680896759033203. Test loss 2.3028745651245117. Test accuracy 0.316008316008316.
2019-04-15 14:54:14,568 INFO: Generation accuracy: 0.30039606362
2019-04-15 14:54:14,568 INFO: Saving model architecture
2019-04-15 14:54:14,569 INFO: Saving model weights
2019-04-15 14:54:14,659 INFO: Done saving model
2019-04-15 14:54:14,659 INFO: Generation 10
2019-04-15 14:54:17,629 INFO: Chunk 0. Each chunk is size 9556
2019-04-15 14:54:17,629 INFO: Train loss 2.335315465927124. Test loss 2.3692831993103027. Test accuracy 0.3228511530398323.
2019-04-15 14:56:54,896 INFO: Generation accuracy: 0.311812696596
2019-04-15 14:56:54,896 INFO: Saving model architecture
2019-04-15 14:56:54,897 INFO: Saving model weights
2019-04-15 14:56:54,985 INFO: Done saving model
2019-04-15 14:56:54,986 INFO: Generation 11
2019-04-15 14:56:57,941 INFO: Chunk 0. Each chunk is size 9599
2019-04-15 14:56:57,941 INFO: Train loss 2.3046693801879883. Test loss 2.3006627559661865. Test accuracy 0.29018789144050106.
2019-04-15 14:59:35,350 INFO: Generation accuracy: 0.310885514402
2019-04-15 14:59:35,350 INFO: Saving model architecture
2019-04-15 14:59:35,350 INFO: Saving model weights
2019-04-15 14:59:35,438 INFO: Done saving model
2019-04-15 14:59:35,438 INFO: Generation 12
2019-04-15 14:59:38,411 INFO: Chunk 0. Each chunk is size 9578
2019-04-15 14:59:38,411 INFO: Train loss 2.2665538787841797. Test loss 2.352621555328369. Test accuracy 0.28661087866108786.
2019-04-15 15:02:15,664 INFO: Generation accuracy: 0.317032510941
2019-04-15 15:02:15,664 INFO: Saving model architecture
2019-04-15 15:02:15,665 INFO: Saving model weights
2019-04-15 15:02:15,755 INFO: Done saving model
2019-04-15 15:02:15,755 INFO: Generation 13
2019-04-15 15:02:18,740 INFO: Chunk 0. Each chunk is size 9544
2019-04-15 15:02:18,740 INFO: Train loss 2.2615725994110107. Test loss 2.2026724815368652. Test accuracy 0.3480083857442348.
2019-04-15 15:04:56,222 INFO: Generation accuracy: 0.317869912327
2019-04-15 15:04:56,222 INFO: Saving model architecture
2019-04-15 15:04:56,223 INFO: Saving model weights
2019-04-15 15:04:56,311 INFO: Done saving model
2019-04-15 15:04:56,311 INFO: Generation 14
2019-04-15 15:04:59,273 INFO: Chunk 0. Each chunk is size 9579
2019-04-15 15:04:59,273 INFO: Train loss 2.2505345344543457. Test loss 2.3359005451202393. Test accuracy 0.28661087866108786.
2019-04-15 15:07:36,728 INFO: Generation accuracy: 0.319010537053
2019-04-15 15:07:36,728 INFO: Saving model architecture
2019-04-15 15:07:36,730 INFO: Saving model weights
2019-04-15 15:07:36,822 INFO: Done saving model
2019-04-15 15:07:36,822 INFO: Generation 15
2019-04-15 15:07:39,787 INFO: Chunk 0. Each chunk is size 9511
2019-04-15 15:07:39,787 INFO: Train loss 2.234037160873413. Test loss 2.2454020977020264. Test accuracy 0.32.
2019-04-15 15:10:17,179 INFO: Generation accuracy: 0.318705093906
2019-04-15 15:10:17,179 INFO: Saving model architecture
2019-04-15 15:10:17,179 INFO: Saving model weights
2019-04-15 15:10:17,270 INFO: Done saving model
2019-04-15 15:10:17,270 INFO: Generation 16
2019-04-15 15:10:20,259 INFO: Chunk 0. Each chunk is size 9567
2019-04-15 15:10:20,259 INFO: Train loss 2.223102331161499. Test loss 2.2645227909088135. Test accuracy 0.3179916317991632.
2019-04-15 15:12:57,742 INFO: Generation accuracy: 0.32238586388
2019-04-15 15:12:57,742 INFO: Saving model architecture
2019-04-15 15:12:57,742 INFO: Saving model weights
2019-04-15 15:12:57,832 INFO: Done saving model
2019-04-15 15:12:57,832 INFO: Generation 17
2019-04-15 15:13:00,815 INFO: Chunk 0. Each chunk is size 9566
2019-04-15 15:13:00,815 INFO: Train loss 2.2629990577697754. Test loss 2.2535746097564697. Test accuracy 0.303347280334728.
2019-04-15 15:15:38,067 INFO: Generation accuracy: 0.325401933309
2019-04-15 15:15:38,067 INFO: Saving model architecture
2019-04-15 15:15:38,068 INFO: Saving model weights
2019-04-15 15:15:38,156 INFO: Done saving model
2019-04-15 15:15:38,156 INFO: Generation 18
2019-04-15 15:15:41,090 INFO: Chunk 0. Each chunk is size 9534
2019-04-15 15:15:41,090 INFO: Train loss 2.227116584777832. Test loss 2.3194327354431152. Test accuracy 0.2815126050420168.
2019-04-15 15:18:18,642 INFO: Generation accuracy: 0.324333137418
2019-04-15 15:18:18,642 INFO: Saving model architecture
2019-04-15 15:18:18,643 INFO: Saving model weights
2019-04-15 15:18:18,734 INFO: Done saving model
2019-04-15 15:18:18,734 INFO: Generation 19
2019-04-15 15:18:21,698 INFO: Chunk 0. Each chunk is size 9553
2019-04-15 15:18:21,698 INFO: Train loss 2.1950695514678955. Test loss 2.2057676315307617. Test accuracy 0.31865828092243187.
2019-04-15 15:20:58,973 INFO: Generation accuracy: 0.33266940697
2019-04-15 15:20:58,973 INFO: Saving model architecture
2019-04-15 15:20:58,973 INFO: Saving model weights
2019-04-15 15:20:59,064 INFO: Done saving model
2019-04-15 15:20:59,064 INFO: Generation 20
2019-04-15 15:21:02,038 INFO: Chunk 0. Each chunk is size 9617
2019-04-15 15:21:02,038 INFO: Train loss 2.1940548419952393. Test loss 2.187612771987915. Test accuracy 0.3541666666666667.
2019-04-15 15:23:39,288 INFO: Generation accuracy: 0.335309421303
2019-04-15 15:23:39,288 INFO: Saving model architecture
2019-04-15 15:23:39,289 INFO: Saving model weights
2019-04-15 15:23:39,376 INFO: Done saving model
2019-04-15 15:23:39,376 INFO: Done!

#####enumerate_config.json#####
{
    "args" : {
        "arch_file" : "arch.json",
        "weight_file" : "weight.h5.20",
        "log_file" : "guess_log.txt",
        "enumerate_ofile": "g1_enumerate.tsv"
    },
    "config" : {
        "training_chunk" : 1000,
        "training_main_memory_chunk": 10000000,
        "min_len" : 3,
        "max_len" : 20,
        "context_length" : 10,
        "chunk_print_interval" : 100,
        "layers" : 3,
        "hidden_size" : 1000,
        "generations" : 20,
        "training_accuracy_threshold" : -1,
        "train_test_ratio" : 20,
        "model_type" : "LSTM",
        "train_backwards" : true,
        "dense_layers" : 2,
        "dense_hidden_size" : 512,
        "secondary_training" : false,
        "simulated_frequency_optimization" : false,
        "randomize_training_order" : true,
        "uppercase_character_optimization" : true,
        "rare_character_optimization" : true,
        "rare_character_optimization_guessing" : true,
        "no_end_word_cache" : true,
        "intermediate_fname" : "intermediate_data.sqlite",
        "save_model_versioned" : true,
        "parallel_guessing": false,
        "lower_probability_threshold": 1e-7,
        "padding_character": true,
        "chunk_size_guesser": 10000,
        "guess_serialization_method": "human",
        "random_walk_seed_num": 100000,
        "max_gpu_prediction_size": 20000,
        "random_walk_seed_iterations": 1,
        "no_end_word_cache": true,
        "char_bag": "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._&@+*!#)-"
    }
}

**Comment by m33x** [comment]
Thanks for the info. I guess you are using the `master` branch with 
Latest commit a749e50  on Nov 30, 2018 ?

**Comment by AiYanLang** [comment]
I used command "git clone https://github.com/cupslab/neural_network_cracking.git" to get the project on April 15th, 2019. I think it is the branch that you said.

**Comment by AiYanLang** [comment]
I used the command "git clone https://github.com/cupslab/neural_network_cracking.git" to get the project on April 15th, 2019. I don't know the specific branch.

**Comment by AiYanLang** [comment]
I solved the problem by appoint the char_bag in train_config too. In addition, train_log have some config that you don't appoint in train_config, if you use them in guess_config, please make them consistent with configs in train_log.
